apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: component-a
  namespace: application-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: component-a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: component-a
    spec:
      containers:
      - image: docker.io/sbose78/foobar:dev-test-df8fjus
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
